// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proiect.Model;

namespace proiect.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210315155226_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("proiect.Model.Cheltuiala", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Suma")
                        .HasColumnType("REAL");

                    b.Property<int>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipCheltuiala")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContId");

                    b.ToTable("cheltuieli");
                });

            modelBuilder.Entity("proiect.Model.Cont", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("conturi");
                });

            modelBuilder.Entity("proiect.Model.Venit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Suma")
                        .HasColumnType("REAL");

                    b.Property<int>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipVenit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContId");

                    b.ToTable("venituri");
                });

            modelBuilder.Entity("proiect.Model.Cheltuiala", b =>
                {
                    b.HasOne("proiect.Model.Cont", null)
                        .WithMany("cheltuieli")
                        .HasForeignKey("ContId");
                });

            modelBuilder.Entity("proiect.Model.Venit", b =>
                {
                    b.HasOne("proiect.Model.Cont", null)
                        .WithMany("venituri")
                        .HasForeignKey("ContId");
                });

            modelBuilder.Entity("proiect.Model.Cont", b =>
                {
                    b.Navigation("cheltuieli");

                    b.Navigation("venituri");
                });
#pragma warning restore 612, 618
        }
    }
}
